trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: gandi-sftp

steps:
- task: CopyFilesOverSSH@0
  inputs:
    host: $(SFTP_HOST)
    port: $(SFTP_PORT)
    username: $(SFTP_USER)
    password: $(SFTP_TOKEN)
    sourceFolder: $(Build.SourcesDirectory)
    contents: |
      **/*
      !.git/**/*
    targetFolder: /www
    overwrite: true