steps:
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'gandi-sftp'
    sourceFolder: $(Build.SourcesDirectory)
    contents: |
      **/*
      !.git/**/*
    targetFolder: /www
    overwrite: true
