table Yes/No
	isHidden
	lineageTag: 699cb16c-d65e-4fb3-9c79-b09b5b83b78e

	column Y/N
		dataType: string
		isHidden
		lineageTag: bc06ffff-c9dc-421d-9b7f-4be59235f51d
		summarizeBy: none
		sourceColumn: Y/N
		sortByColumn: #

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column #
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 90b5016b-af20-4372-a223-a6ed2af69861
		summarizeBy: none
		sourceColumn: #

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Yes/No = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WikwtVtJRMlSK1YlW8ssHMo2UYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Y/N" = _t, #"#" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Y/N", type text}, {"#", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

